#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: commit-task.sh [--message <commit-message>]

Reviews the current dirty worktree at a shell level, ensures a devlog file exists,
stages all tracked/untracked changes, and creates one commit.

Agents should inspect the diff before running this helper when committing
pre-existing dirty parent-branch work.
USAGE
}

MESSAGE=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --message|-m)
      shift
      [ "$#" -gt 0 ] || { echo "Error: --message requires text." >&2; exit 2; }
      MESSAGE="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [ -z "$MESSAGE" ]; then
        MESSAGE="$1"
      else
        echo "Error: unexpected argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
  shift
done

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "Error: run this inside a git repository." >&2
  exit 1
fi

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

BRANCH="$(git branch --show-current)"
if [ -z "$BRANCH" ]; then
  echo "Error: detached HEAD cannot be committed under Agent-Flow." >&2
  exit 1
fi

case "$BRANCH" in
  main|staging|master|production|prod)
    echo "Error: current branch '$BRANCH' is protected or reserved." >&2
    exit 1
    ;;
esac

STATUS="$(git status --short)"
if [ -z "$STATUS" ]; then
  echo "CLEAN: no changes to commit."
  exit 0
fi

if [ -z "$MESSAGE" ]; then
  case "$BRANCH" in
    */*)
      TYPE="${BRANCH%%/*}"
      SUBJECT="${BRANCH#*/}"
      SUBJECT="${SUBJECT//-/ }"
      MESSAGE="$TYPE: $SUBJECT"
      ;;
    *)
      MESSAGE="chore: save $BRANCH worktree"
      ;;
  esac
fi

if ! git diff --check >/dev/null; then
  echo "NOT_READY: git diff --check failed." >&2
  git diff --check || true
  exit 1
fi

devlog_dirty_count="$(git status --short -- devlog 2>/dev/null | wc -l | tr -d ' ')"
if [ "$devlog_dirty_count" = "0" ]; then
  mkdir -p devlog
  date_prefix="$(date +%F)"
  slug="$(printf '%s' "$MESSAGE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
  if [ -z "$slug" ]; then
    slug="agent-flow-commit"
  fi
  devlog_path="devlog/$date_prefix-$slug.md"
  counter=2
  while [ -e "$devlog_path" ]; do
    devlog_path="devlog/$date_prefix-$slug-$counter.md"
    counter=$((counter + 1))
  done

  {
    echo "# $date_prefix - $MESSAGE"
    echo
    echo "- Branch/worktree: \`$BRANCH\` / \`$ROOT\`"
    echo "- Commit: \`pending\`"
    echo "- Goal: Commit reviewed Agent-Flow worktree changes."
    echo "- Summary:"
    echo "  - Captured current worktree changes before continuing Agent-Flow."
    echo "- Files changed:"
    git status --short | sed 's/^/  - `/' | sed 's/$/`/'
    echo "- Decisions:"
    echo "  - Generated by \`scripts/commit-task.sh\` because no devlog change existed."
    echo "- Validation:"
    echo "  - \`git diff --check\` - passed."
    echo "- Review:"
    echo "  - Shell-level diff/stat review required before running this helper."
    echo "- Risks / follow-ups:"
    echo "  - Confirm generated devlog details are sufficient for this change."
  } > "$devlog_path"

  echo "Created devlog: $devlog_path"
fi

echo "== Commit status =="
git status --short
echo
echo "== Diff stat =="
git diff --stat

git add -A
git commit -m "$MESSAGE"
git config "branch.$BRANCH.agentFlowLastCommit" "$(git rev-parse --short HEAD)"

echo "COMMITTED: $(git rev-parse --short HEAD) $MESSAGE"
