#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat >&2 <<'USAGE'
Usage: finish-session.sh [options]

Options:
  --merge              Merge into the recorded parent branch after readiness checks.
  --no-merge           Report readiness only.
  --parent <branch>    Override the recorded parent branch.

Default behavior:
  auto_commit = "finish" commits dirty session work after ensuring a devlog entry exists.
  Ready sessions report ASK_USER_MERGE. Run with --merge only after explicit approval.
USAGE
}

REQUEST_MERGE=0
NO_MERGE=0
PARENT_OVERRIDE=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --merge)
      REQUEST_MERGE=1
      ;;
    --no-merge)
      NO_MERGE=1
      ;;
    --parent)
      shift
      [ "$#" -gt 0 ] || { echo "Error: --parent requires a branch name." >&2; exit 2; }
      PARENT_OVERRIDE="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      usage
      exit 2
      ;;
  esac
  shift
done

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "Error: run this inside a git repository." >&2
  exit 1
fi

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

config_value() {
  local key="$1"
  local default="$2"
  if [ -f ".agent-flow/config.toml" ]; then
    awk -F= -v key="$key" '
      $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
        gsub(/^[[:space:]"]+|[[:space:]"]+$/, "", $2)
        print $2
        found=1
        exit
      }
      END { if (!found) exit 1 }
    ' .agent-flow/config.toml 2>/dev/null || printf '%s\n' "$default"
  else
    printf '%s\n' "$default"
  fi
}

is_protected_branch() {
  case "$1" in
    main|staging|master|production|prod) return 0 ;;
    *) return 1 ;;
  esac
}

MODE="$(config_value mode enforced)"
if [ "$MODE" = "disabled" ]; then
  echo "SKIPPED: Agent-Flow enforcement is disabled by .agent-flow/config.toml."
  exit 0
fi

BRANCH="$(git branch --show-current)"
if [ -n "$BRANCH" ] && is_protected_branch "$BRANCH"; then
  echo "NOT_READY: current branch '$BRANCH' is protected or reserved." >&2
  exit 1
fi

PARENT="${PARENT_OVERRIDE:-$(git config --worktree --get agentFlow.parent 2>/dev/null || true)}"
if [ -z "$PARENT" ] && [ -n "$BRANCH" ]; then
  PARENT="$(git config --get "branch.$BRANCH.agentFlowParent" || true)"
fi
if [ -z "$PARENT" ]; then
  echo "NOT_READY: session worktree has no recorded Agent-Flow parent." >&2
  echo "Create sessions with scripts/start-session.sh or set agentFlow.parent explicitly." >&2
  exit 1
fi

if ! git show-ref --verify --quiet "refs/heads/$PARENT"; then
  echo "NOT_READY: parent branch '$PARENT' does not exist locally." >&2
  exit 1
fi

default_commit_message() {
  local session subject
  session="$(git config --worktree --get agentFlow.sessionName 2>/dev/null || true)"
  if [ -n "$BRANCH" ] && [[ "$BRANCH" == */* ]]; then
    subject="${BRANCH#*/}"
    printf '%s: %s\n' "${BRANCH%%/*}" "${subject//-/ }"
  elif [ -n "$session" ]; then
    printf 'chore: %s\n' "${session//-/ }"
  else
    printf 'chore: finish agent-flow session\n'
  fi
}

ensure_devlog() {
  local message="$1"
  local dirty_count date_prefix slug devlog_path counter branch_label

  dirty_count="$(git status --short -- devlog 2>/dev/null | wc -l | tr -d ' ')"
  if [ "$dirty_count" != "0" ]; then
    return
  fi

  mkdir -p devlog
  date_prefix="$(date +%F)"
  slug="$(printf '%s' "$message" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
  if [ -z "$slug" ]; then
    slug="agent-flow-session"
  fi
  devlog_path="devlog/$date_prefix-$slug.md"
  counter=2
  while [ -e "$devlog_path" ]; do
    devlog_path="devlog/$date_prefix-$slug-$counter.md"
    counter=$((counter + 1))
  done

  if [ -n "$BRANCH" ]; then
    branch_label="$BRANCH"
  else
    branch_label="detached:$(git rev-parse --short HEAD)"
  fi

  {
    echo "# $date_prefix - $message"
    echo
    echo "- Branch/worktree: \`$branch_label\` / \`$ROOT\`"
    echo "- Commit: \`pending\`"
    echo "- Goal: Commit reviewed Agent-Flow session changes."
    echo "- Summary:"
    echo "  - Captured current session changes during finish."
    echo "- Files changed:"
    git status --short | sed 's/^/  - `/' | sed 's/$/`/'
    echo "- Decisions:"
    echo "  - Generated by \`scripts/finish-session.sh\` because no devlog change existed."
    echo "- Validation:"
    echo "  - \`git diff --check\` - passed before commit."
    echo "- Visual/manual proof:"
    echo "  - Not recorded by the helper; update this entry if proof was required."
    echo "- Review:"
    echo "  - Shell-level readiness checks passed before commit."
    echo "- Risks / follow-ups:"
    echo "  - Confirm generated devlog details are sufficient for this change."
  } > "$devlog_path"

  echo "Created devlog: $devlog_path"
}

if [ -n "$(git status --short)" ]; then
  AUTO_COMMIT="$(config_value auto_commit finish)"
  if [ "$AUTO_COMMIT" != "finish" ]; then
    echo "NOT_READY: session worktree has uncommitted or untracked changes." >&2
    git status --short >&2
    exit 1
  fi

  if ! git diff --check >/dev/null; then
    echo "NOT_READY: git diff --check failed." >&2
    git diff --check || true
    exit 1
  fi

  MESSAGE="$(default_commit_message)"
  ensure_devlog "$MESSAGE"

  echo "== Commit status =="
  git status --short
  echo
  echo "== Diff stat =="
  git diff --stat || true

  git add -A
  git commit -m "$MESSAGE"
  git config --worktree agentFlow.lastCommit "$(git rev-parse --short HEAD)"
  git config --worktree agentFlow.lastTouchedAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [ -n "$BRANCH" ]; then
    git config "branch.$BRANCH.agentFlowLastCommit" "$(git rev-parse --short HEAD)"
  fi
  echo "COMMITTED: $(git rev-parse --short HEAD) $MESSAGE"
fi

if ! git diff --check "$PARENT"...HEAD >/dev/null; then
  echo "NOT_READY: git diff --check failed." >&2
  git diff --check "$PARENT"...HEAD || true
  exit 1
fi

AHEAD_COUNT="$(git rev-list --count "$PARENT"..HEAD)"
if [ "$AHEAD_COUNT" = "0" ]; then
  echo "NO_CHANGE: session worktree has no commits ahead of '$PARENT'."
  exit 0
fi

DEVLOG_COUNT="$(git diff --name-only "$PARENT"...HEAD -- 'devlog/*.md' | wc -l | tr -d ' ')"
if [ "$DEVLOG_COUNT" = "0" ]; then
  echo "NOT_READY: no devlog entry changed in this session worktree." >&2
  exit 1
fi

parent_worktree() {
  local target="$1"
  git worktree list --porcelain | awk -v target="refs/heads/$target" '
    /^worktree / { path=substr($0, 10) }
    /^branch / && substr($0, 8) == target { print path; found=1 }
    END { if (!found) exit 1 }
  '
}

PARENT_WORKTREE="$(parent_worktree "$PARENT" || true)"
if [ -z "$PARENT_WORKTREE" ]; then
  echo "NOT_READY: no checked-out worktree found for parent branch '$PARENT'." >&2
  exit 1
fi

if [ -n "$(git -C "$PARENT_WORKTREE" status --short)" ]; then
  echo "NOT_READY: parent worktree '$PARENT_WORKTREE' has uncommitted changes." >&2
  git -C "$PARENT_WORKTREE" status --short >&2
  exit 1
fi

READY_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
git config --worktree agentFlow.state "ready"
git config --worktree agentFlow.finishedAt "$READY_AT"
git config --worktree agentFlow.lastTouchedAt "$READY_AT"
if [ -n "$BRANCH" ]; then
  git config "branch.$BRANCH.agentFlowState" "ready"
  git config "branch.$BRANCH.agentFlowReadyAt" "$READY_AT"
  MERGE_REF="$BRANCH"
else
  MERGE_REF="$(git rev-parse HEAD)"
fi

echo "READY_TO_MERGE"
if [ -n "$BRANCH" ]; then
  echo "Branch: $BRANCH"
else
  echo "Branch: none (detached session worktree)"
  echo "Commit: $(git rev-parse --short HEAD)"
fi
echo "Parent: $PARENT"
echo "Parent worktree: $PARENT_WORKTREE"
echo "Commits ahead: $AHEAD_COUNT"
echo "Devlog files changed: $DEVLOG_COUNT"
echo
git diff --stat "$PARENT"...HEAD

if [ "$REQUEST_MERGE" -ne 1 ] || [ "$NO_MERGE" -eq 1 ]; then
  echo
  echo "ASK_USER_MERGE: run this after approval:"
  echo "  $SCRIPT_DIR/finish-session.sh --merge"
  exit 0
fi

git -C "$PARENT_WORKTREE" merge --no-ff "$MERGE_REF"
MERGED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
git config --worktree agentFlow.state "merged"
git config --worktree agentFlow.mergedAt "$MERGED_AT"
git config --worktree agentFlow.lastTouchedAt "$MERGED_AT"
if [ -n "$BRANCH" ]; then
  git config "branch.$BRANCH.agentFlowState" "merged"
  git config "branch.$BRANCH.agentFlowMergedAt" "$MERGED_AT"
fi

echo "MERGED: ${BRANCH:-$(git rev-parse --short HEAD)} -> $PARENT"
